config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/profile'

  get 'auth/:provider/callback', to: "sessions#create"

  delete 'sign_out', to: "sessions#destroy", as: 'sign_out'

  resources :events
  resources :invites
  resources :users
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :invites,    :foreign_key => :attended_event_id
  has_many :attendees,  through:       :invites

  acts_as_taggable

  geocoded_by :address

  after_validation :geocode, :if => :address_changed?

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :attendee,       :class_name => "User"
  belongs_to :attended_event, :class_name => "Event"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, dependent: :destroy
  has_many :invites,           :foreign_key => :attendee_id
  has_many :attended_events,  through:    :invites


  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name:auth['info']['name']
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_auth

  def authenticate!
     redirect_to root_path unless user_signed_in?
  end

  def user_signed_in?
     !!session[:user_id]
  end

  def current_user
     User.find(session[:user_id])
  end

  def all_users
    @users = User.all
  end

  def get_current_user_location
      #@location_info = request.location
      #@locations = Event.near([@location_info.latitude, @location_info.longitude], 20)
      @locations = Event.near([52.3921183, 16.8979023], 20)
  end

  def update_ip
    current_user.update(ip_address: request.remote_ip)
    current_user.save
  end

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def set_auth
      @auth = session[:omniauth] if session[:omniauth]
    end

    helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_events, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [:index, :show]

  def index
    @events = Event.all.order("date DESC")
    get_current_user_location

    @tagit = ""
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees.all
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(events_params)

    if @event.save
      redirect_to @event
    else
      render "New"
    end
  end

  def update
    if @event.update(events_params)
      redirect_to @event
    else
      render "Edit"
    end
  end

  def edit
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end

  private

    def events_params
      params.require(:event).permit(:name, :description, :address, :max, :date, :latitude, :longitude, :tag_list)
    end

    def find_events
      @event = Event.find(params[:id])
    end

    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def profile
  end
    
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def create
    @event = Event.find(params[:invite][:attended_event_id])
    current_user.invites.create(attended_event_id: @event.id)
    redirect_to @event
  end

  def destroy
    @invite = Invite.find(params[:id])
    current_user.invites.destroy(@invite)
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    session[:omniauth] = auth.except('extra')
    user= User.sign_in_from_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: "SIGNED IN"
  end

  def destroy
    session[:user_id] = nil
    session[:omniauth] = nil
    redirect_to root_url, notice: "SIGNED OUT"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @joined_events = @user.attended_events
    @created_events = @user.events.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_signed_in?
      !!session[:user_id]
     end
     def current_user
        User.find(session[:user_id])
     end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class="row">
	<%= simple_form_for @event do |f| %>

	  <%= f.input :name, placeholder: 'Nazwa...', error: 'Brak nazwy wydarzenia', label: false,
	  	input_html: { class: 'col-lg-offset-3 col-lg-6'}, wrapper: false %>

	  <%= f.input :description, placeholder: 'Treściwy opis wydarzenia...', error: 'Brak opisu wydarzenia.', 
	  	label: false, as: :text, wrapper: false,
	  	input_html: { class: 'col-lg-offset-1 col-lg-6', :rows => 5, :cols => 10}  %>

	  <%= f.input :address, placeholder: 'Lokalizacja (np. ul. Umultowska 87 Poznań)...', label: false, 
	  	error: 'Brak informacji o lokalizacji wydarzenia.', wrapper: false, 
	  	input_html: { class: 'col-lg-offset-1 col-lg-4'} %>


		<!-- <%= f.input :max, label: 'Maksymalna liczba uczestników:', error: 'Brak informacji o maksymalnej liczbie uczestników.', wrapper: false,
	  	input_html: { class: 'col-lg-1'},
	  	label_html: { class: 'col-lg-offset-1 col-lg-3' } %> -->

	  <!-- <%= f.datetime_local_field :date, label: 'Data wydarzenia:', error: 'Brak informacji o dacie wydarzenia.',
	  	input_html: { class: 'col-lg-1'}, wrapper: true,
	  	label_html: { class: 'col-lg-offset-1 col-lg-3' } %> -->

	  <!-- <%= f.input :tag_list, placeholder: 'Tagi (separowane przecinkami)', label: false,
	  	error: 'Nie podano żadnego tagu (min. 1).', wrapper: false,
	  	input_html: { class: 'col-lg-offset-1 col-lg-4' } %> -->
	  	
	  <label for="event_date" class="col-lg-2">Data wydarzenia</label>
	  <input type="datetime-local" class="col-lg-2" name="event[date]" id="event_date" />


	  <br>
	  <%= f.submit "Utwórz wydarzenie", :class => "form-btn col-lg-offset-5 col-lg-2" %>
	<% end %>
	  <%= link_to "Powrót do wydarzeń", events_path, :class => "form-btn col-lg-2" %>
</div>

app/views/events/edit.html.erb
<div class="title row">
	<h1 class="col-lg-12">Edytuj wydarzenie</h1>
</div>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="title row">
	<h1 class="col-lg-12">Najbliższe wydarzenia!</h1>
</div>

<!-- <div class="searchbox row">
	<div class="hashtags search-tags col-lg-6">
		<span class="hashtag search-tag">#sport</span>
		<span class="hashtag search-tag">#piłka nożna</span>
		<span class="hashtag search-tag">#boisko</span>		
	</div>	
</div> -->


<div class="evnt-results row">
	<% @locations.each do |location| %>
		<div class="evnt-result row">
			<div class="evnt-img col-lg-1">
				<%= link_to image_tag("keep_temporary.png", size: "100", class: 'evnt-photo')%>				
			</div>
			
			<div class="evnt-descr col-lg-8">
				<div class="evnt-name row">
					<%=  link_to location.name, location %>
				</div>
			</div>
			

			<div class="evnt-info col-lg-3">
				<label>Adres:</label>
				<p><%= location.address %></p>
				<!--<p>ul. Żymierskiego 5<br>66-200 Świebodzin</p>-->
				
				<label>Godzina rozpoczęcia: </label>
				<p><%= location.date %></p>
				<!--<p>03:14</p>-->
			</div>
		</div>
	<% end %>
</div>


<!-- <% @locations.each do |location| %>
	<%= location.name %>
<% end %> -->

app/views/events/new.html.erb
<div class="title row">
	<h1 class="col-lg-12">Nowe wydarzenie</h1>
</div>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
  <div class="col-lg-12 title">
    <h1><%= @event.name %></h1>
  </div>
  <!-- <div class="col-lg-offset-3 col-lg-6 hashtags">
    <span class="hashtag">#tag</span>
    <span class="hashtag">#tag</span>
    <span class="hashtag">#tag</span>
  </div> -->
</div>

<div class="row">
  <div class="col-lg-6">
    <div class="row evnt-info">
      <h3>Opis</h3>
      <p class="evnt-descr"><%= @event.description %></p>
    </div>

    <br>

    <div class="row">
      <div class="col-lg-5  evnt-info">
        <h3>Adres</h3>
        <p><%= @event.address %></p>
      </div>
      <div class="col-lg-offset-2 col-lg-5  evnt-info">
        <h3>Data i godzina</h3>
        <p><%= @event.date %></p>
      </div>
    </div>
  </div>
  
  <div class="col-lg-3">
    <div class="row">
      <div class="col-lg-offset-1 col-lg-10 evnt-info">
        <h3>Lista uczestników</h3>
        <ul class="pull-left evnt-usr-list">
          <% @attendees.each do |attendee| %>
            <li><%= attendee.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-lg-3">
    <div class="row evnt-info">
      <div class="col-lg-12">
        <h3>Organizator</h3>
        <p class="pull-left"><%= @event.user.name %></p>
      </div>
    </div>
    
    <div class="row evnt-info" style="margin-top: 5%">
      <ul class="evnt-controlls">
        <% if user_signed_in? %>
          <% if current_user.id == @event.user_id %>
            <li>
              <i class='fa fa-pencil'></i>
              <%= link_to "Edit", edit_event_path(@event) %>
            </li>
            <li>
              <i class="fa fa-trash"></i>
              <%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?"} %>
            </li>
          <% else %>
          	<% if @event.attendees.include?(current_user) %>
              <li>
                <i class="fa fa-minus"></i>
                <%= simple_form_for(current_user.invites.find_by(attended_event_id: @event.id), :html => { :method => :delete }) do |f| %>
                  <%= f.submit "Odejdź" %>
                <% end %>
              </li>
            <% else %>
              <li>
                <i class="fa fa-plus"></i>
                <%= simple_form_for(current_user.invites.build(attended_event_id: @event.id)) do |f| %>
                  <%= f.hidden_field :attended_event_id, :value => @event.id %>
                    <%= f.submit "Dołącz" %>
                <% end %>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="wrapper">
	<div class="evnt-logo">
		Evnt.
	</div>

	<nav class="evnt-nav">
		<ul>
			<% if user_signed_in? %>
				<div class="user-part">
					<li>
						<span class="left-part">
							<i class="fa fa-list"></i>
						</span>
						<%= link_to "Moje wydarzenia", current_user %>
					</li>
					<li>
						<span class="left-part">
							<i class="fa fa-plus-square"></i>
						</span>
						<%= link_to "Dodaj wydarzenie", new_event_path %>
					</li>
					<li>
						<span class="left-part">
							<i class="fa fa-sign-out"></i>
						</span>
						<%= link_to "Wyloguj się", 'sign_out', method: :delete %>
					</li>
				</div>
			<% else %>
				<div class="user-part">
					<li>
						<span class="left-part">
							<i class="fa fa-sign-in"></i>
						</span>
						<%= link_to "Zaloguj się", "auth/facebook" %>
					</li>
				</div>
			<% end %>

			<li>
				<span class="left-part">
					<i class="fa fa-calendar"></i>
				</span>
				<%= link_to "Wydarzenia", events_path %>
			</li>
		</ul>
	</nav>
</div>

app/views/home/profile.html.erb
<h1>Home#profile</h1>
<p>Find me in app/views/home/profile.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
	<span class="sexy_line"></span>
	<div class="pull-left">Evnt. Team 2015</div>
	<ul class="">
		<li class="pull-right">Kontakt</li>
		<li class="pull-right">Regulamin</li>
	</ul>
</footer>

app/views/layouts/_header.erb
<header>
  <nav>
    <ul>
      <li id="evnt-logo">
        <!-- <a href="/">Evnt.</a> -->
      </li>

      <% if current_user %>
        <li class="pull-right">
            <a href="/"><%= current_user.name  %></a>
        </li>
        <li class="pull-right">
            <%= image_tag(@auth['info']['image'], class: 'img-circle') %>
        </li>
        <li class="pull-right">
          <%= link_to "Wyloguj się", 'sign_out', method: :delete %>
        </li>
      <% else %>
        <li class="pull-right facebook"><%= link_to "auth/facebook" do %><i class="fa fa-facebook"></i><% end %></li>
      <% end %>

    </ul>
    <span class="sexy_line"></span>
  </nav>
</header>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul>
      <li id="evnt-logo">
        <a href="/">Evnt.</a>
      </li>

      <% if current_user %>
        <li class="pull-right">
            <a href="/"><%= current_user.name  %></a>
        </li>
        <li class="pull-right">
            <%= image_tag(@auth['info']['image'], class: 'img-circle') %>
        </li>
        <li class="pull-right">
          <%= link_to "Wyloguj się", 'sign_out', method: :delete %>
        </li>
      <% else %>
        <li class="pull-right facebook"><%= link_to "auth/facebook" do %><i class="fa fa-facebook"></i><% end %></li>
      <% end %>

      <li class="pull-right">
        <!-- <%= link_to raw('<i class="fa fa-calendar"></i>'), events_path %> -->
        <%= link_to "Wydarzenia", events_path %>
      </li>
    </ul>
    <span class="sexy_line"></span>
  </nav>
</header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h1><%= link_to root_path do %>Evnt.<% end %></h1>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= current_user.name  %> - <%= image_tag(@auth['info']['image'], width: '50', heigth: '50', class: 'img-circle') %> </li>
          <li><%= link_to "Sign Out", 'sign_out', method: :delete %></li>
        <% else %>
          <li><%= link_to "auth/facebook" do %><%= image_tag('facebook.png', width: '40', heigth: '40', class: 'img-circle') %><% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evnt</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- jquery -->
    <script   src="https://code.jquery.com/jquery-2.2.2.min.js"   integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI="   crossorigin="anonymous"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <!-- Awesome fonts! -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body>

    <% if current_page?(controller: 'home', action: 'index') %>
    <% else %>
      <%= render "layouts/header" %>
    <% end%>
    
    <main>
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/users/show.html.erb
<div class="row title">
  <h1>Moje wydarzenia </h1>
</div>

<div class="row">
  <div class="col-lg-6 col-lg-offset-3 my-evnts">
    <h3>Wydarzenia, w których bierzesz udział.</h3>
    <span class="sexy_line"></span>
    <% if @joined_events.empty? %>
      <p>W najbliższym czasie nie bierzesz udziału w żadnych wydarzeniach. 
      <%= link_to "Przejrzyj najnowsze!", events_path  %></p>
    <% else %>
      <ul>
        <% @joined_events.each do |event| %>
          <li>
            <%= link_to "#{event.name}", event_path(event) %>
            <%= event.date %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <h3>Wydarzenia, które organizujesz.</h3>
    <span class="sexy_line"></span>
    <% if @created_events.empty? %>
      <p>W najbliższym czasie nie organizujesz żadnych wydarzeń.</p>
    <% else %>
      <ul>
        <% @created_events.each do |event| %>
          <li>
            <%= link_to "#{event.name}", event_path(event) %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>